function simpleGUI
% Create figure
h.f = figure('units','pixels','position',[200,200,500,500],...
             'toolbar','none','menu','none');
% Create yes/no checkboxes for all time
h.c(1) = uicontrol('style','checkbox','units','pixels',...
                'position',[10,400,150,15],'string','All PTs as subplot',...
                'Value',1);
h.c(2) = uicontrol('style','checkbox','units','pixels',...
                'position',[10,380,150,15],'string','PT1',...
                'Value',1);
h.c(3) = uicontrol('style','checkbox','units','pixels',...
                'position',[10,360,150,15],'string','PT2',...
                'Value',1); 
h.c(4) = uicontrol('style','checkbox','units','pixels',...
                'position',[10,340,150,15],'string','PT3',...
                'Value',1);
h.c(5) = uicontrol('style','checkbox','units','pixels',...
                'position',[10,320,150,15],'string','PT4',...
                'Value',1);
h.c(6) = uicontrol('style','checkbox','units','pixels',...
                'position',[10,300,150,15],'string','PT5',...
                'Value',1);
h.c(7) = uicontrol('style','checkbox','units','pixels',...
                'position',[10,280,150,15],'string','PT6',...
                'Value',1);
h.c(8) = uicontrol('style','checkbox','units','pixels',...
                'position',[10,260,150,15],'string','PT7',...
                'Value',1);
h.c(9) = uicontrol('style','checkbox','units','pixels',...
                'position',[10,240,150,15],'string','Force',...
                'Value',1);
% Create yes/no checkboxes for burn time
h.b(1) = uicontrol('style','checkbox','units','pixels',...
                'position',[100,400,150,15],'string','All PTs as subplot',...
                'Value',1);
h.b(2) = uicontrol('style','checkbox','units','pixels',...
                'position',[100,380,150,15],'string','PT1',...
                'Value',1);
h.b(3) = uicontrol('style','checkbox','units','pixels',...
                'position',[100,360,150,15],'string','PT2',...
                'Value',1); 
h.b(4) = uicontrol('style','checkbox','units','pixels',...
                'position',[100,340,150,15],'string','PT3',...
                'Value',1);
h.b(5) = uicontrol('style','checkbox','units','pixels',...
                'position',[100,320,150,15],'string','PT4',...
                'Value',1);
h.b(6) = uicontrol('style','checkbox','units','pixels',...
                'position',[100,300,150,15],'string','PT5',...
                'Value',1);
h.b(7) = uicontrol('style','checkbox','units','pixels',...
                'position',[100,280,150,15],'string','PT6',...
                'Value',1);
h.b(8) = uicontrol('style','checkbox','units','pixels',...
                'position',[100,260,150,15],'string','PT7',...
                'Value',1);
h.b(9) = uicontrol('style','checkbox','units','pixels',...
                'position',[100,240,150,15],'string','Force',...
                'Value',1);
%Create checkbox for table
h.a(1) = uicontrol('style','checkbox','units','pixels',...
                'position',[190,400,150,15],'string','Table',...
                'Value',1);
% Create get data pushbutton   
h.pbdata = uicontrol('style','pushbutton','units','pixels',...
                'position',[40,95,150,20],'string','Choose data file',...
                'callback',@file_call);  
    % Pushbutton callback
    function file_call(varargin)
        [baseName, folder] = uigetfile('*.csv');
        global fullFileName
        fullFileName = fullfile(folder, baseName);
    end        
% Create get Nominal data pushbutton   
h.pbNomdata = uicontrol('style','pushbutton','units','pixels',...
                'position',[40,50,150,20],'string','Choose Nominal data file',...
                'callback',@Nomfile_call);  
    % Pushbutton callback
    function Nomfile_call(varargin)
        [baseName, folder] = uigetfile('*.xlsx');
        global fullNomFileName
        fullNomFileName = fullfile(folder, baseName);
    end  
% Create OK pushbutton   
h.pbgo = uicontrol('style','pushbutton','units','pixels',...
                'position',[40,5,70,20],'string','GO',...
                'callback',@p_call);
    % Pushbutton callback
    function p_call(varargin)
        vals1 = get(h.c,'Value');
        global yesGraph
        yesGraph = [vals1{:}];
        
        vals2 = get(h.b,'Value');
        global yesGraphBurn
        yesGraphBurn = [vals2{:}];
        
        vals3 = get(h.a,'Value');
        global yesTable
        yesTable = vals3;
        
        %continue running script
        uiresume
        %close GUI window
        close(h.f)
    end
end